name: Release Wither Derive
on:
  push:
    tags:
      - "wither-derive-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Setup | Create Release Log
        run: cat CHANGELOG.md | tail -n +7 | head -n 25 > RELEASE_LOG.md

      - name: Build | Publish Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_LOG.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build | Publish Wither Derive
        run: cd wither_derive && cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
